# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build Firstjob
    - bash: echo $(PipeLineLevelVariable)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  # - job: SecondJob
  #   steps:
  #   - bash: echo Build SecondJob
   
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: build
#   jobs:
#   - job: DeployJob
#     steps:
#     - bash: echo $(environment)Deploy

# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: build
#   jobs:
#   - job: DeployJob
#     steps:
#     - bash: echo $(environment)deploy
    
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: DeployJob
#     steps:
#     - bash: echo $(environment)Deploy

