

trigger:
- master

# strategy:
#  matrix:
#   linux: 
#     operatingSystem: 'ubuntu-latest'
#   mac:
#     operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build 
  jobs:
  - job: BuildJob
    steps: 
    - bash: echo "Do teh build" 
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJobs
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to dev 

- stage: QADeploy
  jobs:
  - deployment: DevDeployJobs
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy toQA




